export const POOL = {
  RECEIVE_INFORMATION: 'pool/RECEIVE_INFORMATION',
  RECEIVE_MESSAGES: 'pool/RECEIVE_MESSAGES',
  RECEIVE_BULLETINS: 'pool/RECEIVE_BULLETINS',
  CLEAR: 'pool/CLEAR',
  UPDATE_MEMBERPAID: 'pool/UPDATE_MEMBERPAID',
  REMOVE_MEMBERSHIP: 'pool/REMOVE_MEMBERSHIP',
  RECEIVE_BUYIN: 'pool/RECEIVE_BUYIN',
  RECEIVE_NAME: 'pool/RECEIVE_NAME'
};
