export const POOL = {
  RECEIVE_INFORMATION: 'pool/RECEIVE_INFORMATION',
  RECEIVE_MESSAGES: 'pool/RECEIVE_MESSAGES',
  RECEIVE_BULLETINS: 'pool/RECEIVE_BULLETINS',
  CLEAR: 'pool/CLEAR',
  REMOVE_MY_POOL: 'pool/REMOVE_MY_POOL'
};
