# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a98880fb711adc73b48f8a0871d644bc9f2c75a31669091ce29c5aaed577932ef48a2e5cf9b228de6661aff8d6cfd46a41591d72cc9e0fb3197b7d218adb2fd

staging:
  secret_key_base: fe433a99f8db7582e300a125c4e3463340101564708c14455650f35cbdb43b575331c38aae6f2dd6a4f9e8d2d2f2753f6274758eddee2d4600aac9620fe8ce78

test:
  secret_key_base: eb07f27db5ce45f1630e61c83316128a4e6666dae3d8b389fe16f2df9157fe56ae55ee66621b78787e0407ed659b14d385c0869500a18d99b229ed851c728049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
